services:
  go-dev:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    init: true
    hostname: <PROJECT_NAME>
    environment:
      - PROJECT_NAME=<PROJECT_NAME>
      - SHELL=/bin/bash
      - GOCACHE=/go/.cache/go-build
      - GOENV=/go/.config/go/env
    volumes:
      - ../src/:/go/src
      - ../pkg/:/go/pkg
      - ../.cache/:/go/.cache
      - ../.config/:/go/.config
      - ../.devcontainer/:/.devcontainer
      - ~/.ssh/:/home/dev/.ssh:ro
    command: ["/.devcontainer/init.sh"]
